server.port: 8001
au.com.ontheboat.hosts:
  api: http://localhost:8081
  keycloak: http://localhost:8080
spring:
  cloud:
    gateway.globalcors.cors-configurations:
      '[/**]':
        allowedOrigins: "http://localhost:3000"
        allowedMethods:
          - GET
          - POST
          - PUT