server.port: 8001
au.com.ontheboat.hosts:
  api: http://marina-api:8081
spring:
  cloud:
    gateway.globalcors.cors-configurations:
      '[/**]':
        allowedOrigins: "*"
        allowedMethods:
          - GET
          - POST
          - PUT